# Generated by Django 3.2.7 on 2022-04-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfchecks',
            name='estado',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('a pagar', 'A Pagar'), ('anulado', 'Anulado')], default='a pagar', max_length=50),
        ),
    ]
