# Generated by Django 3.2.7 on 2022-02-03 20:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='campaña', unique=True, unique_for_date='fecha_inicio')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateTimeField(default=datetime.datetime.now)),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('cerrada', 'Cerrada')], default='vigente', max_length=50)),
            ],
            options={
                'ordering': ('-fecha_inicio',),
            },
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='campo', max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('propio', 'Propio'), ('alquilado', 'Alquilado')], default='propio', max_length=9)),
                ('estado', models.CharField(choices=[('en explotación', 'En explotación'), ('alquilado', 'Alquilado')], default='en explotación', max_length=14)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='land.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('hectareas', models.IntegerField()),
                ('tipo', models.CharField(choices=[('soja', 'Soja'), ('maiz', 'Maiz'), ('trigo', 'Trigo'), ('girasol', 'Girasol'), ('sorgo', 'Sorgo'), ('centeno', 'Centeno'), ('cebada', 'Cebada'), ('avena', 'Avena'), ('arroz', 'Arroz')], max_length=7)),
                ('slug', models.SlugField(unique=True)),
                ('campaña', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='land.campaign')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.land')),
            ],
        ),
    ]
