# Generated by Django 3.2.7 on 2021-12-28 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='campaña', unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('cerrada', 'Cerrada')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='campo', max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('propio', 'Propio'), ('alquilado', 'Alquilado')], default='propio', max_length=9)),
                ('estado', models.CharField(choices=[('en explotación', 'En explotación'), ('alquilado', 'Alquilado')], default='en explotación', max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('numero', models.IntegerField()),
                ('hectareas', models.IntegerField()),
                ('tipo', models.CharField(choices=[('soja', 'Soja'), ('maiz', 'Maiz'), ('trigo', 'Trigo'), ('girasol', 'Girasol'), ('sorgo', 'Sorgo'), ('centeno', 'Centeno'), ('cebada', 'Cebada'), ('avena', 'Avena'), ('arroz', 'Arroz')], max_length=50)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.land')),
            ],
        ),
    ]
