# Generated by Django 3.2.7 on 2022-04-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='estado',
            field=models.CharField(choices=[('cosechado', 'Cosechado'), ('no cosechado', 'No cosechado')], default='no cosechado', max_length=12),
        ),
    ]
