# Generated by Django 3.2.7 on 2021-12-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_land_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='estado',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('cerrada', 'Cerrada')], default='vigente', max_length=50),
        ),
    ]
