# Generated by Django 3.2.7 on 2021-12-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0003_alter_campaign_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(default='campaña', unique=True, unique_for_date='fecha_inicio'),
        ),
    ]
