# Generated by Django 3.2.7 on 2021-12-28 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0004_alter_campaign_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
