# Generated by Django 3.2.7 on 2021-12-29 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0005_alter_campaign_fecha_inicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ('-fecha_inicio',)},
        ),
    ]
