# Generated by Django 3.2.7 on 2022-01-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0007_lote_capaña'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='capaña',
            new_name='campaña',
        ),
    ]
