# Generated by Django 3.2.7 on 2022-01-24 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0008_rename_capaña_lote_campaña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='campaña',
        ),
    ]
