# Generated by Django 3.2.7 on 2022-01-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0009_remove_lote_campaña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='tipo',
            field=models.CharField(choices=[('soja', 'Soja'), ('maiz', 'Maiz'), ('trigo', 'Trigo'), ('girasol', 'Girasol'), ('sorgo', 'Sorgo'), ('centeno', 'Centeno'), ('cebada', 'Cebada'), ('avena', 'Avena'), ('arroz', 'Arroz')], max_length=7),
        ),
    ]
