# Generated by Django 3.2.7 on 2022-06-06 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sowing', '0002_remove_sowingpurchases_campo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sowingpurchases',
            name='producto',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.CreateModel(
            name='ProductsRows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lt_kg', models.FloatField()),
                ('product', models.CharField(max_length=100)),
                ('precio_lt_kg_usd', models.FloatField(default=0)),
                ('SowingPurchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sowing.sowingpurchases')),
            ],
        ),
    ]
