# Generated by Django 3.2.7 on 2022-06-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowing', '0003_auto_20220606_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='sowingpurchases',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
