# Generated by Django 3.2.7 on 2022-06-07 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sowing', '0004_sowingpurchases_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsrows',
            old_name='SowingPurchase',
            new_name='sowing_purchase',
        ),
    ]
