# Generated by Django 3.2.7 on 2021-10-06 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('slug', models.SlugField(max_length=250, unique_for_date='date')),
            ],
        ),
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_kg', models.IntegerField(blank=True, max_length=250, null=True)),
                ('price_head', models.IntegerField(blank=True, max_length=250, null=True)),
                ('total_kg', models.IntegerField(blank=True, max_length=250, null=True)),
                ('iva', models.IntegerField(blank=True, max_length=250, null=True)),
                ('category', models.CharField(choices=[('terneros', 'Terneros'), ('terneras', 'Terneras'), ('novillos', 'Novillos'), ('vaquillonas', 'Vaquillonas'), ('vacas', 'Vacas')], default='terneros', max_length=15)),
                ('buy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.purchases')),
            ],
        ),
    ]
