# Generated by Django 3.2.7 on 2021-10-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='iva',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=200),
        ),
        migrations.AddField(
            model_name='animal',
            name='price_kg',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=200),
        ),
        migrations.AlterField(
            model_name='animal',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
