# Generated by Django 3.2.7 on 2021-10-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='categoría',
            field=models.CharField(choices=[('ternero', 'Ternero'), ('ternera', 'Ternera'), ('novillo', 'Novillo'), ('vaquillona', 'Vaquillona'), ('vaca', 'Vaca')], default='ternero', max_length=500),
        ),
        migrations.AlterField(
            model_name='animal',
            name='precio_por_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200),
        ),
    ]
