# Generated by Django 3.2.7 on 2021-10-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20211028_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200),
        ),
    ]
