# Generated by Django 3.2.7 on 2021-10-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_alter_animal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
