# Generated by Django 3.2.7 on 2021-10-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_animal_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='slug',
        ),
    ]
