# Generated by Django 3.2.7 on 2021-11-01 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_auto_20211028_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ('categoria',)},
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='categoría',
            new_name='categoria',
        ),
    ]
