# Generated by Django 3.2.7 on 2022-04-20 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg_totales', models.PositiveIntegerField(default=0)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.lote')),
            ],
        ),
    ]
