# Generated by Django 3.2.7 on 2022-04-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='kg_totales',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
