# Generated by Django 3.2.7 on 2022-09-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_fundmanualmove_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeOutcomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250, unique_for_date='date')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default='Descripción...', max_length=350)),
                ('operador', models.CharField(max_length=350)),
                ('factura', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='fundmanualmove',
            name='description',
            field=models.CharField(default='Descripción...', max_length=250),
        ),
    ]
