# Generated by Django 3.2.7 on 2022-09-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_auto_20220905_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeoutcomes',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], default='ingreso', max_length=250),
        ),
    ]
