# Generated by Django 3.2.7 on 2022-09-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_incomeoutcomes_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeoutcomes',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
