# Generated by Django 3.2.7 on 2021-11-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundmanualmove',
            name='action',
            field=models.CharField(choices=[('agregar', 'Agregar'), ('quitar', 'Quitar')], default='agregar', max_length=250),
        ),
    ]
