# Generated by Django 3.2.7 on 2022-08-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0002_grainmanualmove'),
    ]

    operations = [
        migrations.AddField(
            model_name='grainmanualmove',
            name='tipo',
            field=models.CharField(choices=[('agregado', 'Agregado'), ('quitado', 'Quitado')], default='agregado', max_length=8),
        ),
    ]
