# Generated by Django 3.2.7 on 2022-01-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorsedchecks',
            name='third_p_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
