# Generated by Django 3.2.7 on 2021-11-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ('-date',)},
        ),
    ]
