# Generated by Django 3.2.7 on 2021-11-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_selfchecks'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfchecks',
            name='slug',
            field=models.SlugField(default='ckeck', max_length=250, unique_for_date='fecha_salida'),
        ),
        migrations.AlterField(
            model_name='selfchecks',
            name='estado',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('a pagar', 'A Pagar')], default='a pagar', max_length=50),
        ),
    ]
