# Generated by Django 3.2.7 on 2021-12-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20211125_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartychecks',
            name='slug',
            field=models.SlugField(default='ckeck', max_length=250, unique_for_date='fecha_ingreso'),
        ),
    ]
