# Generated by Django 3.2.7 on 2021-12-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_endorsedchecks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endorsedchecks',
            name='estado',
            field=models.CharField(choices=[('depositado', 'Depositado'), ('a depositar', 'A depositar'), ('endosado', 'Endosado')], default='endosado', max_length=50),
        ),
    ]
