# Generated by Django 3.2.7 on 2021-12-28 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SowingPurchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250, unique_for_date='date')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('factura', models.CharField(blank=True, max_length=100)),
                ('proveedor', models.CharField(max_length=100)),
                ('producto', models.CharField(max_length=100)),
                ('precio_lt_kg_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lt_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pagado', 'Pagado'), ('por pagar', 'Por pagar')], max_length=50)),
                ('tipo_cambio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('campaña', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.campaign')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.land')),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250, unique_for_date='date')),
                ('date', models.DateTimeField()),
                ('numero', models.IntegerField()),
                ('lt_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.lote')),
            ],
        ),
    ]
