# Generated by Django 3.2.7 on 2022-03-09 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
        ('sowing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other_Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.lote')),
            ],
        ),
    ]
