# Generated by Django 3.2.7 on 2021-12-29 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sowingpurchases',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
