# Generated by Django 3.2.7 on 2022-04-26 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sowing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sowingpurchases',
            name='campo',
        ),
    ]
