# Generated by Django 3.2.7 on 2021-12-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowing', '0002_alter_sowingpurchases_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sowingpurchases',
            name='estado',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('por pagar', 'Por pagar')], default='por pagar', max_length=50),
        ),
        migrations.AlterField(
            model_name='sowingpurchases',
            name='factura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
