# Generated by Django 3.2.7 on 2022-04-04 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sowing', '0002_other_expenses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sowingpurchases',
            old_name='estado',
            new_name='status',
        ),
    ]
