# Generated by Django 3.2.7 on 2021-12-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowing', '0003_auto_20211229_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sowingpurchases',
            name='precio_lt_kg_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
