# Generated by Django 3.2.7 on 2022-01-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sowing', '0004_alter_sowingpurchases_precio_lt_kg_usd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sowingpurchases',
            options={'ordering': ('-date',)},
        ),
    ]
