# Generated by Django 3.2.7 on 2022-01-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowing', '0005_alter_sowingpurchases_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sowingpurchases',
            name='iva',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sowingpurchases',
            name='lt_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sowingpurchases',
            name='precio_lt_kg_usd',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sowingpurchases',
            name='tipo_cambio',
            field=models.FloatField(default=0),
        ),
    ]
