# Generated by Django 3.2.7 on 2022-01-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowing', '0006_auto_20220124_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='producto',
            field=models.CharField(choices=[('glifosato', 'Glifosato'), ('boral', 'Boral')], default='glifosato', max_length=30),
        ),
    ]
