# Generated by Django 3.2.7 on 2022-01-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowing', '0007_applications_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='producto',
            field=models.CharField(default='glifosato', max_length=30),
        ),
    ]
