# Generated by Django 3.2.7 on 2021-11-01 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salerow',
            options={'ordering': ('categoria',)},
        ),
        migrations.RenameField(
            model_name='salerow',
            old_name='categoría',
            new_name='categoria',
        ),
    ]
