# Generated by Django 3.2.7 on 2022-04-20 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrainSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('grano', models.CharField(choices=[('soja', 'Soja'), ('maiz', 'Maiz'), ('trigo', 'Trigo'), ('girasol', 'Girasol'), ('sorgo', 'Sorgo'), ('centeno', 'Centeno'), ('cebada', 'Cebada'), ('avena', 'Avena'), ('arroz', 'Arroz')], max_length=7)),
                ('precio_tn', models.FloatField()),
                ('iva', models.FloatField()),
                ('camionero', models.CharField(max_length=100)),
                ('patente', models.CharField(max_length=50)),
                ('kg_bruto', models.FloatField()),
                ('kg_tara', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('cobrado', 'Cobrado'), ('por cobrar', 'Por cobrar')], default='por cobrar', max_length=15)),
                ('iva_status', models.CharField(choices=[('cobrado', 'Cobrado'), ('por cobrar', 'Por cobrar')], default='por cobrar', max_length=15)),
                ('slug', models.SlugField(max_length=250, unique_for_date='fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Retentions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ganancias', 'Ganancias'), ('iva', 'IVA'), ('ingresos brutos', 'Ingresos Brutos')], max_length=15)),
                ('monto', models.FloatField()),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.grainsales')),
            ],
        ),
        migrations.CreateModel(
            name='Deductions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=50)),
                ('base_calculo', models.FloatField()),
                ('iva', models.FloatField()),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.grainsales')),
            ],
        ),
    ]
