# Generated by Django 3.2.7 on 2021-11-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20211101_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='status',
            field=models.CharField(choices=[('cobrado', 'Cobrado'), ('por cobrar', 'Por cobrar')], default='por cobrar', max_length=15),
        ),
    ]
