# Generated by Django 3.2.7 on 2022-04-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_deductions_grainsales_retentions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grainsales',
            name='slug',
        ),
    ]
