# Generated by Django 3.2.7 on 2021-12-28 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250, unique_for_date='date')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('ternero', 'Ternero'), ('ternera', 'Ternera'), ('novillo', 'Novillo'), ('vaquillona', 'Vaquillona'), ('vaca', 'Vaca')], default='ternero', max_length=500)),
                ('cantidad', models.IntegerField(default=0)),
                ('tipo', models.CharField(choices=[('agregado', 'Agregado'), ('quitado', 'Quitado')], default='agregar', max_length=500)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.land')),
            ],
        ),
    ]
