# Generated by Django 3.2.7 on 2021-11-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualmove',
            name='tipo',
            field=models.CharField(choices=[('agregado', 'Agregado'), ('quitado', 'Quitado')], default='agregar', max_length=500),
        ),
    ]
