# Generated by Django 3.2.7 on 2021-11-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250, unique_for_date='date')),
                ('concepto', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descripcion', models.CharField(max_length=250)),
                ('categoria', models.CharField(choices=[('costos directos', 'Costos Directos'), ('gastos de comercializacion', 'Gastos de Comercializacion'), ('gastos financieros', 'Gastos financieros'), ('costos de estructura', 'Costos de estructura'), ('impuestos', 'Impuestos')], default='costos directos', max_length=70)),
                ('status', models.CharField(choices=[('pagado', 'Pagado'), ('por pagar', 'Por pagar')], default='por pagar', max_length=15)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
