# Generated by Django 3.2.7 on 2022-04-26 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grainsales',
            options={'ordering': ('-fecha',)},
        ),
    ]
